spring:
  application:
    name: product-service

  datasource:
    url: jdbc:postgresql://localhost:5432/product
#    url: jdbc:mysql://localhost:3306/productdb
#    url: jdbc:postgresql://ep-wispy-heart-adyd86ek-pooler.c-2.us-east-1.aws.neon.tech/product?sslmode=require&channel_binding=require
    username: abhinav # neondb_owner
    password: abhinav #npg_k7XZvNOwB6gq
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect



server:
  port: 8081
